# Generated by Django 4.2.1 on 2023-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "todo"),
                    ("2", "in_progress"),
                    ("3", "review"),
                    ("4", "completed"),
                    ("5", "cancel"),
                ],
                verbose_name="STATUS",
            ),
        ),
    ]
