# Generated by Django 4.2.1 on 2023-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtask",
            name="task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="subtask",
        ),
        migrations.AddField(
            model_name="task",
            name="subtask",
            field=models.ManyToManyField(to="tasks.subtask"),
        ),
    ]
